<?php

namespace AppBundle\Controller\EasyAdmin;

use AppBundle\Entity\User;

class UserController extends AdminController
{
  /**
   * @param User $entity
   */
  protected function preUpdateEntity($entity /*, bool $ignoreDeprecations = false */) {
    $entity->setUpdatedAt(new \DateTime());
//    return parent::preUpdateEntity($entity); // TODO: Change the autogenerated stub
  }

}
