app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

# app/config/routing.yml
easy_admin_bundle:
    resource: "@AppBundle/Controller/EasyAdmin/AdminController.php"
    type:     annotation
    prefix:   /easyadmin
